apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-ssh
spec:
  containers:
  - name: ssh-container
    image: iamclyde/ssh:latest
    command: ["/usr/sbin/sshd", "-D"]
    ports:
    - containerPort: 22 # Expose port 22 for SSH
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh-service
spec:
  selector:
    app: ubuntu-ssh # Label selector to match your Pod
  ports:
  - name: ssl
    protocol: TCP
    port: 22
    targetPort: 22 # Target port of the Pod (SSH)
  type: LoadBalancer # Expose the Service externally
